spring:
  config:
    activate:
      on-profile: local
  
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:19093

  docker:
    compose:
      enabled: true
      file: docker-compose.yml
