server:
  port: 8082

spring:
  application:
    name: microservice-book
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: microservice-book
        instance-id: ${spring.application.name}:${server.port}
